inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/main/ci/rubocop.yml
  - .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'examples/**/*'
  inherit_mode:
    merge:
      - Exclude
